# Perform a release in response to tag creation

trigger:
  tags:
    include:
    - releases/*

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    npm install
    npm run build
    set
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false

- task: GitHubRelease@0
  inputs:
    action: edit
    tag: 'releases/$(build.sourceBranchName)'
    gitHubConnection: 1ESDayReleases
    repositoryName: AzureBoardsTeam/1ESDay
